# mysql
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-gamesales
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: gamesales
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
